const API_READ_ACCESS_TOKEN = "eyJhbGciOiJIUzI1NiJ9.eyJhdWQiOiI4OTFkODVmOWU0NjY1YTQ3MzU2M2EyYTM3YTExNjY3NSIsIm5iZiI6MTYwMjEzODU2NS42MTUsInN1YiI6IjVmN2ViMWM1YzgxMTNkMDAzNmFlOTRmNyIsInNjb3BlcyI6WyJhcGlfcmVhZCJdLCJ2ZXJzaW9uIjoxfQ.KWXYD8yrQLDpM5EaDs5R0Qnb46wXkkavVR2i_g0Ga4A"

const HEADER_AUTH = {
    headers : {
        Authorization: `Bearer ${API_READ_ACCESS_TOKEN}`
    }
};

export {
    API_READ_ACCESS_TOKEN,
    HEADER_AUTH
}